name: sealed_class_generator
description: Sealed Class generator parses and generates your sealed classes.
version: 1.0.0
author: Tim Rijckaert <tim.rijckaert@gmail.com>

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  build: ^1.2.1
  source_gen: ^0.9.4+6
  sealed_class:
    path: ../sealed_class/
  
dev_dependencies:
  build_test: ^0.10.9+1
  build_runner: ^1.7.1
  test: ^1.9.3